package io.github.susimsek.springbootjweauthjpademo.dto.request;

import io.github.susimsek.springbootjweauthjpademo.validation.annotation.TotpCode;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

@Schema(
    name        = "VerifyTotpRequest",
    description = "Request payload containing the 6-digit TOTP code to verify"
)
public record VerifyTotpRequestDTO(

    @Schema(
        description = "The 6-digit TOTP code generated by the authenticator app",
        example     = "123456"
    )
    @NotBlank
    @Size(min = 6, max = 6)
    @TotpCode
    String code

) {}
